# Base NumPy


Exercice avec Numpy sur Spyder :

1. Importer numpy as np
2. Créer un vecteur nommé vector grâce à .array contenant les nombres suivants : 3, 4, 18, 60 puis l’afficher
3. Créer une matrice nommée matrix avec .array, comprenant 3 lignes et 3 colonnes :
    - Ligne 1 : 1, 2, 3
    - Ligne 2 : 4, 5, 6
    - Ligne 3 : 7, 8, 9
4. Afficher matrix
5. Afficher la taille de vector puis de matrix à l’aide de .shape
6. Créer une liste de liste dans la var list_of_list avec [5, 10, 15] et [20, 25, 30] puis l’afficher 
7. Créer une matrice nommée matrix_2 avec 2 lignes et 3 colonnes :
    - Ligne 1 : 1, 2, 3 
    - Ligne 2 : 4, 5, 6
8. Afficher le 6
9. Afficher toutes les lignes de la 2ème colonne
10. Afficher la 2ème ligne


In [1]:
import numpy as np

In [2]:
vector = np.array([3, 4, 18, 60])
print(vector)

[ 3  4 18 60]


In [4]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
vector.shape

(4,)

In [6]:
list_of_list = ([[5,10, 15], [20, 25, 30]])
print(list_of_list)

[[5, 10, 15], [20, 25, 30]]


In [30]:
matrix_2 = np.array([[1, 2, 3], [4, 5, 6]])

In [31]:
matrix_2[1,2]

6

In [32]:
matrix_2[:,1]

array([2, 5])

In [35]:
matrix_2[1,0:3]

array([4, 5, 6])